################################################################################
# Node-RED Stack or Compose
################################################################################
# docker-compose [-f docker-compose.yml] -p myGateway up
################################################################################
version: "3.3"

services:
  node-red:
    container_name: nodered
    image: ghcr.io/tulsasoftware/ucontrol-genesis-tag-service:${TAG_SERVICE_TAG}
    environment:
      - TZ=US/Central
    ports:
      #DEV GUI WILL LIVE ON 3080
      - "3080:1880"
    depends_on:
      - influxdb
      - broker
      - couchdb
    networks:
      - node-red-net
    volumes:
      - ../../ucontroldata/nodered:/data
    restart: unless-stopped
  couchdb:
    container_name: settings
    image: couchdb:3.2.2
    env_file:
      - ".env"
    ports:
      - "5984:5984"
    networks:
      - node-red-net
    volumes:
      #expose the db files on the host machine
      - ../../ucontroldata/couchdb/:/opt/couchdb/data
    restart: always
    #on launch, create the default system databases
    # command: ["sh", "-c", "/opt/couchdb/bin/couchdb & { sleep 3 ; curl -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_IP}:5984/_users ; curl -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_IP}:5984/_replicator ; fg ; }"]

  # Creates an InfluxDB instance to store the telemetry results
  influxdb:
    image: influxdb:1.8.10
    restart: always
    networks:
      - node-red-net
    volumes:
      - ../../ucontroldata/influxdb/:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASS}
      - INFLUXDB_DB=telemetry
  # mqtt broker
  broker:
    image: emqx/nanomq:0.11.0
    restart: always
    networks:
      - node-red-net
    ports:
      - "1883:1883"
      - "8883:8883"
#Manage the influxdb
  chronograf:
    image: chronograf:latest
    restart: always
    networks:
      - node-red-net
    volumes:
      # Mount for chronograf database
      - ../../ucontroldata/chronograf/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb

networks:
  node-red-net: